model-checking/verify-rust-std

.reuse/dep5

*Description of changes:*
Add file for copyright checks based on the upstream version of the same file. This way we keep the format for the library folder.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Add copyright check file

---

.github/workflows/book.yml
doc/src/tools/kani.md

Fix the book script and add a little blob to the Kani page.

Fix the book script

---

.gitmodules
README.md

*Issue #, if available:*
*Description of changes:*
Adds disclaimer that this project is not endorsed by Rust foundation and fixes license links.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Add disclaimer, and fix links

---

.github/workflows/book.yml
.github/workflows/kani.yml
.github/workflows/rustc.yml
rust-toolchain.toml

Create two new workflows:
- Rust Tests: Run the Rust repository tests for the standard library.
- Kani: Run `kani verify-std` to verify the standard library. Note that we don't have any harness yet to verify.

Add Rust tests and Kani workflow

---

doc/src/SUMMARY.md
doc/src/general-rules.md
doc/src/intrinsics-memory.md
doc/src/template.md

Adds the challenge to `Verify the memory safery of core intrinsics using raw pointers`

Add Challenge 2: Verify the memory safery of core intrinsics using raw pointers

---

.github/workflows/book.yml
.github/workflows/kani.yml
.github/workflows/rustc.yml

With path-based filters for CI jobs we cannot consistently use branch protection as jobs marked "required" wouldn't necessarily run on a given PR.

Run CI checks on all PRs against to main

---

library/core/src/intrinsics.rs
library/core/src/mem/mod.rs

Add contracts to `core::mem::swap` and `core::intrinsics::typed_swap`.

Add a few more contract and harness examples

---

.github/CODEOWNERS
.github/dependabot.yml
.github/workflows/book.yml
.github/workflows/kani.yml
.github/workflows/rustc.yml
.gitignore
doc/book.toml
library/contracts/safety/Cargo.toml
rust-toolchain.toml

Removes copyright strings, and allows this project to be in contribution model sync with upstream.

Remove copyright strings

---

.github/ISSUE_TEMPLATE/tracking_issue.md

Creates an issue template for new issues that are for tracking challenges. 
Right now, anyone can add a tracking issue for a challenge without the link to the challenge in the runbook.
This template will help remind them of the order of creation which would be to first, create the challenge in the runbook, then create the tracking issue.

Add tracking issue for challenges template

---

.github/pull_requests.toml
doc/src/general-rules.md

This PR adds 
1. An empty committee `toml` file as a cache that will be used by the CI workflow to check if the approvers belong to the committee.
2. Some simple guidelines for users to apply to become a part of the committee.

Add committee application guideline and committee TOML file

---

doc/src/SUMMARY.md
doc/src/challenges/0003-pointer-arithmentic.md

In this challenge, we want to look at the safe usage of pointer arithmetic operations.

Propose a new challenge about pointer arithmetic ops

---

doc/src/SUMMARY.md
doc/src/challenges/0005-linked-list.md

> Please add a description of your PR.
> If this is a solution to an open challenge, please explain your solution.
>
> Don't forget to check our book to ensure your solution satisfy the overall
> requirements as well as the challenge success criteria.
>

Add a challenge for `linked_list`

---

.github/workflows/pr_approval.yml

Fixes: https://github.com/model-checking/verify-rust-std/actions/runs/9878423942/job/27283663117 which is a 403 error from github.
[Source for fix](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac)
Test: https://github.com/jaisnan/rust-dev/pull/22/checks?check_run_id=27285370500

Add permissions needed to modify PR

---

library/core/src/alloc/layout.rs
library/core/src/ptr/alignment.rs

These contracts seek to capture what is described in documentation and debug assertions.

Add contracts for Layout and Alignment

---

library/core/src/ascii/ascii_char.rs
library/core/src/char/convert.rs
library/core/src/char/methods.rs

Add contracts for `char_try_from_u32`, `from_u32_unchecked`, `from_u8_unchecked`, `from_u8`, and `as_ascii`.

char and ascii_char contracts

---

.github/TOOL_REQUEST_TEMPLATE.md
README.md

> Please add a description of your PR.
> If this is a solution to an open challenge, please explain your solution.
>
> Don't forget to check our book to ensure your solution satisfy the overall
> requirements as well as the challenge success criteria.
>
Resolves #ISSUE-NUMBER

Introduce tool template

---

.github/pull_requests.toml

Add "ranjitjhala" and "carolynzech" to commitee toml

Add "ranjitjhala" and "carolynzech" to commitee

---

.github/workflows/pr_approval.yml

Simplify pr workflow to require 2 approvals on all PR's
All PR's will need 2 approvals from the commitee for this check to pass. 
A more intelligent approach is on the way, but till then all PR's will need 2 approvals.
This is done to prevent sneak attacks where someone gets approval for non-std related changes, and after approval, they make changes to the std files.
Failed check after just 1 approver :- https://github.com/jaisnan/rust-dev/actions/runs/10583003063
Successful check after 2nd approver :- https://github.com/jaisnan/rust-dev/actions/runs/10583018556

Simplify pr workflow to require 2 approvals on all PR's

---

doc/book.toml

Remove all section numbers to prevent confusing labelling.
This is what the book looks like after this change

Remove all section numbers to prevent confusing labelling

---

.github/workflows/pr_approval.yml

Prevent pr approval from getting skipped when there is a non-approval review submitted on the PR.

Prevent skipping due to "if" statement

---

library/core/src/ptr/unique.rs

Modifies the `check_cast` harness to:
- Be a proof instead of a proof for contract
- Remove the generic type parameter
Currently, Kani doesn't run this harness. (See the [log](https://github.com/model-checking/verify-rust-std/actions/runs/10887990165/job/30211482361?pr=85) from a recent PR). It doesn't run the harness because it has a generic type parameter, and Kani's error handling for contract proofs doesn't check for this condition. (PR to fix is [here](https://github.com/model-checking/kani/pull/3522)). Once we remove the generic type parameter so that the harness runs, Kani complains that we can't run it as a proof for contract because there are no contracts, so we make it a regular proof instead.
By submitting this pull request, I confirm that my contribution is made under the …

Fix check_cast harness

---

doc/src/tools/kani.md

Minor changes to documentation to clarify some confusion and make it more accessible.
Related to :- https://github.com/model-checking/verify-rust-std/pull/85

Improve documentation with links and additional steps

---

library/core/src/ptr/mod.rs

Currently, this harness takes 21 minutes in CI. The only point of this harness is to verify the contract for pointee types with a non-power of two byte size--17 was an arbitrary choice. Reducing to 5 and changing the solver reduces verification time to 57 seconds on my local machine.

Improve performance for align offset harness

---

doc/src/tools/kani.md

This PR adds to the documentation in the Verification Tools->Kani section of the [challenge book](https://model-checking.github.io/verify-rust-std/tools/kani.html).
- Step 1: add clarify on where to put the example code.
- Step 2: add `-Z mem-predicate` to avoid unstable feature errors.
- Step 4: new step to help kani user run specific proofs and identify harness fullnames.
I tried to follow step 1 & 2 but kani could not find the harnesses in the example code. At this point there are many proofs in the library so I couldn't find the fullname of the harness in the example code by just running all proofs. I tried to move `example.rs` into `library/core/src/ptr/` and use `--harness ptr::verify::example` or `--harness dummy_proof` but both got `error: no harnesses matched the harness filter`. …

Add documentation to run Kani on single harnesses

---

library/core/src/num/mod.rs

Towards : issue #59
Parent branch : main 
Revalidation : 
Per the discussion in https://github.com/model-checking/verify-rust-std/issues/59, we have to build and run Kani from feature/verify-rust-std branch.
To revalidate the verification results, run the following command. <harness_to_run> can be either num::verify to run all harnesses or num::verify::<harness_name> (e.g. widening_mul_u16_small) to run a specific harness.
```
kani verify-std  "path/to/library" \
--harness <harness_to_run> \
-Z unstable-options \
-Z function-contracts \
-Z mem-predicates
```

Contracts & Harnesses for widening_mul

---

library/core/src/num/int_macros.rs
library/core/src/num/mod.rs
library/core/src/num/uint_macros.rs

Towards #59 
* Added contracts for `wrapping_shl` (located in `library/core/src/num/int_macros.rs` and `uint_macros.rs`)
* Added a macro for generating wrapping_{shl, shr} harnesses
* Added harnesses for `wrapping_shl` of each integer type
* `i8`, `i16`, `i32`, `i64`, `i128`, `isize`, `u8`, `u16`, `u32`, `u64`, `u128`, `usize` --- 12 harnesses in total.
1. Per the discussion in #59, we have to **build and run Kani from `feature/verify-rust-std` branch**.
2. To revalidate the verification results, run the following command. `<harness_to_run>` can be either `num::verify` to run all harnesses or `num::verify::<harness_name>` (e.g. `checked_wrapping_shl_i8`) to run a specific harness.
```
kani verify-std  "path/to/library" \
--harness <harness_to_run> \
-Z unstable-options \
-Z …
```

Contracts & Harnesses for `wrapping_shl`

---

README.md

To test that the link works, navigate to [my fork](https://github.com/carolynzech/verify-rust-std/tree/fix-readme) and click the tool template link in the README.

Fix tool template link in README

---

library/alloc/Cargo.toml
library/alloc/src/lib.rs
library/std/Cargo.toml
library/std/src/lib.rs

Just as previously done for core: this will enable future use of `safety::{ensures,requires}` in those crates.

Add safety dependency to alloc and std crates

---

library/core/src/slice/iter.rs
library/core/src/slice/iter/macros.rs
library/core/src/ub_checks.rs

This PR implements the invariant for `Iter` and `IterMut` and contains harnesses for some `Iter` methods. I commented out a bunch of harnesses that are currently failing until I can debug them further.
I am planning to add harnesses for `IterMut` later, but I could use some early feedback. Thanks!

Start the verification of `slice::Iter`

---

tool_config/kani-version.toml

Update to the version where the CBMC viewer is removed. This should resolve the issues some people are having with the `run_kani.sh` script.

Update Kani version

---

doc/src/challenges/0005-linked-list.md

This PR, just fixes a typo for a function name in the challenge docs.

docs(0005): typo fix in the challenge docs

---

README.md
doc/src/challenge_template.md
doc/src/challenges/0001-core-transmutation.md
doc/src/challenges/0002-intrinsics-memory.md
doc/src/challenges/0003-pointer-arithmentic.md
doc/src/challenges/0004-btree-node.md
doc/src/challenges/0005-linked-list.md
doc/src/challenges/0006-nonnull.md
doc/src/challenges/0007-atomic-types.md
doc/src/challenges/0008-smallsort.md
doc/src/challenges/0009-duration.md
doc/src/challenges/0010-string.md
doc/src/challenges/0011-floats-ints.md
doc/src/challenges/0012-nonzero.md
doc/src/challenges/0013-cstr.md
doc/src/intro.md

I also postponed the end date of all challenges, and fixed the date format.

Add reward information to the repository and challenges

---

library/core/src/ffi/c_str.rs
library/core/src/ffi/mod.rs

Towards #150 
* Added a `CStr` Safety Invariant
* Added a harness for `from_bytes_until_nul`, the harness covers:
* The input slice contains a single null byte at the end;
* The input slice contains no null bytes;
* The input slice contains intermediate null bytes
* [Safety invariant implementation](https://github.com/model-checking/verify-rust-std/issues/150#issuecomment-2492853570)
* [Input array generation](https://github.com/model-checking/verify-rust-std/discussions/181)
`./scripts/run-kani.sh --kani-args --harness ffi::c_str::verify`
```
// array size 16
Checking harness ffi::c_str::verify::check_from_bytes_until_nul...
VERIFICATION RESULT:
** 0 of 140 failed (5 unreachable)
VERIFICATION:- SUCCESSFUL
Verification Time: 7.3023376s
Complete - 1 successfully verified harnesses, 0 …
```

CStr Safety invariant & Harnesses for `from_bytes_until_nul`

---

library/core/src/ffi/c_str.rs

Towards #150 
* Added harnesses for `to_bytes` and `to_bytes_with_nul`
* Added a small fix to `count_bytes`
Verification Result:
```
Checking harness ffi::c_str::verify::check_to_bytes_with_nul...
VERIFICATION RESULT:
** 0 of 179 failed (5 unreachable)
VERIFICATION:- SUCCESSFUL
Verification Time: 88.397385s
Checking harness ffi::c_str::verify::check_to_bytes...
VERIFICATION RESULT:
** 0 of 180 failed (5 unreachable)
VERIFICATION:- SUCCESSFUL
Verification Time: 79.66312s
Checking harness ffi::c_str::verify::check_from_bytes_until_nul...
VERIFICATION RESULT:
** 0 of 132 failed (5 unreachable)
VERIFICATION:- SUCCESSFUL
Verification Time: 28.593569s
Complete - 3 successfully verified harnesses, 0 failures, 3 total.
```
By submitting this pull request, I confirm that my contribution is made …

Harnesses for `to_bytes` and `to_bytes_with_nul`

---

library/core/src/slice/iter.rs
library/core/src/str/pattern.rs

In #148 and #122, we had to comment out a few harnesses due to the issue https://github.com/model-checking/kani/issues/3670. But now that the fix has been pushed, we can enable them.

Enable harnesses that were blocked by Kani's spurious CEX

---

.github/workflows/book.yml
.github/workflows/kani.yml
.github/workflows/pr_approval.yml
.github/workflows/rustc.yml

Add `merge_group` as a trigger for our workflows. For the review check workflow, I also added a review dismissed option, and for the `merge_group` case, the workflow does nothing.

Prepare repo for enabling merge queue

---

.github/workflows/kani.yml
scripts/run-kani.sh

Update the `kani list` part of our workflow to:
- Be its own step of the workflow so it can run in parallel, which is nice because it finishes much faster than the other jobs in the Kani workflow
- Use the new markdown format. This makes the list much more readable (compare [current format](https://github.com/model-checking/verify-rust-std/actions/runs/12199714877/attempts/2#summary-34034201022) to [markdown format](https://github.com/carolynzech/verify-rust-std/actions/runs/12203155221/attempts/1#summary-34045490103)).
Also remove the Test Kani workflow step, because it's expensive and duplicates verification work.

Kani Workflow Updates

---

library/core/src/slice/iter.rs

With https://github.com/model-checking/kani/issues/3670 having been addressed we re-enabled harnesses in #211. Yet the comment explaining previously-commented-out-harnesses stayed in place.
Removing it for it no longer applies.

Cleanup stray comment

---

library/core/src/num/nonzero.rs

Working on [#71](https://github.com/model-checking/verify-rust-std/issues/71) (Safety of NonZero)
We are looking for feedback on our proof for rotate_left & rotate_right.

NonZero (rotate_left, rotate_right, max, min, clamp, count_ones, cmp) Proofs

---

.github/workflows/pr_approval.yml

The `check_approvals` workflow in #107 fails because by default Github [only returns the first 30 results](https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28#about-pagination) for GET requests to their API. #107 has more review activity than that, so the approvals are all on the second or third pages, hence why the workflow says zero approvals.
So, this PR updates the script to fetch 100 responses per page, up to 100 pages. These are arbitrary values, but I didn't want to have any infinite loops, and I can't imagine a realistic PR ever going above these numbers (and I put a warning in the script if they do).
I checked that this new workflow runs without error [on my fork](https://github.com/carolynzech/verify-rust-std/actions/runs/1226 …

PR Approvals Workflow: Fetch Multiple Pages

---

.github/ISSUE_TEMPLATE/tool_application.md
doc/src/general-rules.md
doc/src/tool_template.md

This PR updates the tool application section of our book. The key changes are:
- Specify how to submit tool applications (through an issue). Also provide a "Tool Application" issue template.
- Move the details about specifying differences with other tools and audit information to the application so they're harder to miss.
(These changes are inspired by our experience with the [Verifast application](https://github.com/model-checking/verify-rust-std/issues/213); I realized there's a few things we can make clearer on our end).

Update tool application section of book

---

doc/src/SUMMARY.md

Update the summary title so it's the same as the title in the challenge itself.

Fix Atomic Challenge typo

---

doc/src/general-rules.md

Extends committee membership information with guidance on what is expected of committee members.

Add review guidelines

---

doc/src/SUMMARY.md

This PR fixes a minor typo in `SUMMARY.md` I noticed while browsing through the site.

Fix intrinsics challenge typo in summary

---

README.md
doc/src/general-rules.md

We now have the foundation's endorsement for this work.

Remove non-endorsement note

---

.github/workflows/kani.yml
scripts/run-kani.sh

Shard Kani verification workflow across multiple runners by:
1. Running `kani list --format json`, which outputs a JSON file like this:
```json
{
"kani-version": "0.56.0",
"file-version": "0.1",
"standard-harnesses": {
"src/lib.rs": [
"proof3",
"verify::proof2"
],
"src/test.rs": [
"test::proof4",
"test::proof5"
]
},
"contract-harnesses": {
"src/lib.rs": [
"proof"
]
},
"contracts": [
{
"function": "bar",
"file": "src/lib.rs",
"harnesses": [
"proof"
]
}
],
"totals": {
"standard-harnesses": 4,
"contract-harnesses": 1,
"functions-under-contract": 1
}
}
```
2. Extracting the harnesses inside `"standard-harnesses"` and `"contract-harnesses"` into an array called `ALL_HARNESSES` and the length of that array into `HARNESS_COUNT`. (So in this example, `ALL_HARNESSES = [proof3, verify::proof2, …

Parallelize & Partition Verification

---

library/core/src/num/mod.rs

This harness takes between 22-25 minutes in CI. Change the harnesses's macro to use kissat solver instead, which brings verification time down to ~7 seconds.
As an aside, I noticed this problem because the partition 1 runner in #229 is taking ~55 minutes, where the other partitions are taking ~30 minutes. This harness accounts for almost the entire difference. One nice consequence of partitioning verification is that it will make performance issues like this more noticeable.

Improve `u16::carrying_mul` harness performance

---

scripts/run-kani.sh

Fix a typo introduced in #229 that prevents `kani-args` from getting passed to the `kani` command.
This was discovered by @tengjiang (see https://github.com/model-checking/verify-rust-std/discussions/231).

Add missing line separator

---

.github/workflows/goto-transcoder.yml
.gitignore
doc/src/tools.md
doc/src/tools/goto-transcoder.md
rust-toolchain.toml
scripts/run-goto-transcoder.sh

Resolves #108
This PR enables the use of goto-transcoder for the following contracts:
```
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_add_i8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_add_u8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_mul_i8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_mul_u8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_shl_i8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_shl_u8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unchecked_shr_i8.out
core-58cefd8dce4133f9__RNvNtNtCs9uKEoH8KKW4_4core3num6verify24checked_unc …
```

Goto-transcoder action

---

library/core/src/intrinsics/mod.rs

This is a pull request towards solving #19. 
- Added wrappers for `transmute_unchecked()` 
- Annotated these wrappers with contracts
- Wrote harnesses that verify these wrappers
Note: the reason we write wrappers for `transmute_unchecked()` and we annotate those wrappers is that function contracts do not appear to be currently supported for compiler intrinsics (as discussed in [#3345](https://github.com/model-checking/kani/issues/3345)). Also, rather than using a single wrapper for `transmute_unchecked()`, we write several with different constraints on the input (since leaving the function parameters completely generic severely restricts what we can do in the contracts, e.g., testing for equality).
This is not intended to be a complete solution for verifying `transmute_unchecked()`, but …

transmute_unchecked contracts and harnesses

---

library/core/src/convert/num.rs

Add harnesses for safety of primitive conversions

---

.github/workflows/update-subtree.yml

There should not be a need for manual processes for the first stage of the subtree update, i.e., updating our subtree/library branch.
Merge conflicts (which might require a human to intervene) will only happen once attempting to merge from subtree/library back into main. Automation for this stage has been added, will create a PR separate from the above one, and will likely require manual intervention.

Automate subtree update

---

.github/workflows/update-subtree.yml

repo-filter does not produce consistent SHA hashes. While we were aware of this, we hadn't realized that this made incremental non-interactive updates of the branch a matter of luck as git may or may not be able to automatically resolve conflicts. (It worked for the update to 2025-02-10, but failed for the next one.)
git-subtree-split does produce consistent SHA hashes, but the native `git-subtree-split` implementation is a shell script, and thus was found to be too slow (which is why we chose repo-filter in the first place).
splitsh-lite is an implementation of just the `subtree split` command in Go and libgit2. This makes `subtree split` even faster than `repo-filter` at 35 seconds vs 50 seconds (on a GitHub runner).
By submitting this pull request, I confirm that my contribution is …

Subtree update automation: use fast version of subtree split

---

doc/src/challenges/0015-intrinsics-simd.md

https://model-checking.github.io/verify-rust-std/challenges does not autoconvert github issue links

Fix link rendering in 0015-intrinsics-simd.md

---

.github/workflows/update-subtree.yml

`git subtree merge --squash` will always reset the subtree to the state of the tree that is being merged from, which effectively eradicates all our local changes. This was just masked by merge conflicts arising as we were always attempted to merge from some long-ago version as we hadn't consistently kept "git-subtree-split" markers.
This PR now amends the pull request descriptions to make sure we retain the necessary information and uses `git merge` instead of the subtree command.

Subtree update automation: do not use `git subtree merge --squash`

---

.github/workflows/verifast-negative.yml
.github/workflows/verifast.yml
verifast-proofs/README.md
verifast-proofs/alloc/collections/linked_list.rs-negative/original/linked_list.rs
verifast-proofs/alloc/collections/linked_list.rs-negative/verified/linked_list.rs
verifast-proofs/alloc/collections/linked_list.rs/original/linked_list.rs
verifast-proofs/alloc/collections/linked_list.rs/verified/linked_list.rs
verifast-proofs/check-verifast-proofs-negative.mysh
verifast-proofs/check-verifast-proofs-negative.sh
verifast-proofs/check-verifast-proofs.mysh
verifast-proofs/check-verifast-proofs.sh
verifast-proofs/patch-verifast-proofs.sh

Updates the VeriFast proofs after `linked_list.rs` was modified by https://github.com/rust-lang/rust/commit/c39f33baae94665d69a45d45a00d0dc028c80cc9 .
Also:
- Added a bash script that attempts to automatically patch the proofs after the original file was changed.
- The VeriFast CI actions now produce an error alert suggesting to run this script, if a source file that is the subject of a VeriFast proof is changed.

Sync the VeriFast proofs and provide guidance on same

---

library/core/src/num/saturating.rs
library/core/src/num/wrapping.rs
library/portable-simd/crates/core_simd/src/vector.rs

Implement `kani::Arbitrary` for the `Wrapping`, `Saturating`, and `Simd` types.

Implement kani::Arbitrary for Wrapping, Saturating, and Simd types

---

.github/workflows/kani.yml
scripts/run-kani.sh

Run https://github.com/carolynzech/autoharness_analyzer and push its results to the job summary.

Add autoharness-analyzer CI job

---

.github/workflows/pr_approval.yml

We are making a lot of changes to our `scripts/` and `.github/workflows/` folders to improve automation. These changes are low-risk; we have no plans to upstream them and they're not part of the public-facing challenge effort. Update our workflow to require two committee approvals iff `doc/`, `library/` or `verifast-proofs/` are modified, and otherwise just require one.
See https://github.com/carolynzech/rust/pull/35 and https://github.com/carolynzech/rust/pull/36 for test runs on my fork.

Only require two approvals for changes to `doc/`, `library/` or `verifast-proofs/`

---

library/core/src/ptr/const_ptr.rs

I was grepping for contract and this one didn't match because of the typo. Minor comment-only change.

Fix typo in comment ('contact' -> 'contract')

---

library/core/src/num/nonzero.rs

The result of a rotate operation is always non-zero, which could still be less than zero in case of signed types.
Proofs were failing with the prior contract, but this still passed CI as we haven't yet picked up the Kani version where autoharness exits with a non-zero exit code in case of proof failure.

Fix num::nonzero::NonZero::<*>::rotate_{left,right} contracts

---

.github/workflows/update-subtree.yml
verifast-proofs/patch-verifast-proofs.sh

When preparing a merge subtree PR, try to patch the VeriFast proofs.
Also tweaks `patch-verifast-proofs.sh` to ensure that no temporary files are left behind inside the working directory, even when the script fails mid-way.
Note: I did not test this.

update-subtree action: patch VeriFast proofs

---

.github/workflows/update-subtree.yml

PR #371 introduced invalid bash syntax ("line 51: syntax error near unexpected token `fi'").

Fix subtree update action

---

scripts/run-kani.sh

`--enable-unstable` has been removed from Kani's latest version and will, thus, break upgrading to a newer Kani version.

Kani: use -Z unstable-options instead of --enable-unstable

---

.github/workflows/update-subtree.yml

Update submodules to the exact version that upstream uses at the commit that we are trying to merge towards. We never modify the contents of submodules, so we don't need to make any attempt to merge changes and instead can directly pick the right upstream version.
See https://github.com/tautschnig/verify-rust-std/actions/runs/15846078305/job/44668465448 for a successful run and https://github.com/tautschnig/verify-rust-std/pull/25 for the ensuing PR (which, notably, includes [a commit that bumps submodules](https://github.com/tautschnig/verify-rust-std/pull/25/commits/54d1d407a20917a07729abd602d9d0c3f67a335f)).

Subtree update automation: update submodules

---

.github/workflows/update-subtree.yml

While the prior fixes made sure that submodule changes are picked up, the attempt to commit would fail when there were _no_ changes. See https://github.com/model-checking/verify-rust-std/actions/runs/15878565075/job/44772389751 for a failing run.
Now we will only attempt to commit when there are changes.

Fix subtree automation for submodules when there were no changes

---

.github/workflows/update-subtree.yml

Currently, I receive a workflow run failure notification in my mailbox every day because this workflow runs in my fork.

Don't run update-subtree.yml in forks

---

.github/workflows/flux.yml
doc/src/SUMMARY.md
doc/src/tools/flux.md
library/core/Cargo.toml
library/core/src/ascii/ascii_char.rs
library/core/src/convert/num.rs
library/core/src/flux_info.rs
library/core/src/lib.rs

This PR introduces Flux to the list of tools used in the book and adds a corresponding CI workflow.
The CI workflow runs Flux on a subset of `core` (specifically, files under `src/ascii`) to verify the absence of array out-of-bounds errors. It demonstrates how to annotate the code with refinement types to specify the pre- and post-conditions necessary to prove safety on the subset that Flux is enabled.
The Flux tool and necessary dependencies are built from source on CI (pinning specific commits).
Resolves https://github.com/model-checking/verify-rust-std/issues/362

Add Flux tool description and CI workflow

---

doc/src/challenges/0025-vecdeque.md

Fixes a broken Markdown table in the Challenge 25 description.

Fix table in 0025-vecdeque.md

---

doc/src/challenges/0020-str-pattern-pt1.md

The description for Challenge 20 did not show correctly on GitHub Pages due to missing line breaks after an enumeration. This PR adds those missing line breaks.

Add missing line breaks in 0020-str-pattern-pt1.md

---

scripts/run-goto-transcoder.sh

The previous link for ESBMC is now dead, breaking the CI. This updates goto transcoder to use the latest version of ESBMC.

Update ESBMC link

---

.github/workflows/kani-metrics.yml

Fork repos will auto run this job, thus bot PRs are weekly created due to autoharness and frequent API changes in libstd.
So this commit disables the job for fork repos.

ci: only run update-kani-metrics in model-checking/verify-rust-std

---

.github/workflows/verifast-negative.yml
.github/workflows/verifast.yml
verifast-proofs/alloc/collections/linked_list.rs/verified/linked_list.rs

The RawVec proof needs 25.07.
Also, a recent upstream change in `linked_list.rs` broke the proof. I fixed it and upgraded it to 25.07.
To avoid conflicts between the two proof PRs, I'm submitting the VeriFast bump as a separate PR.

Bump VeriFast to 25.07

---

doc/src/tools.md

This is a fix-up to #403, where Flux was integrated into CI. While at it, also make that list of tools lexicographically sorted.

Add Flux to list of approved tools

---

library/core/Cargo.toml
library/core/src/ascii/ascii_char.rs
library/core/src/flux_info.rs
library/core/src/num/mod.rs
library/core/src/num/niche_types.rs
library/core/src/num/uint_macros.rs
library/core/src/pat.rs

This PR adds flux specifications for checking the following modules in core
* pat
* bstr
* hash
* time
In particular, it verifies that `Nanoseconds` is correctly used with values within the range. 

Add Flux specifications to path/bstr/hash/time

---

verifast-proofs/alloc/raw_vec/mod.rs/original/raw_vec.rs
verifast-proofs/alloc/raw_vec/mod.rs/verified/raw_vec.rs
verifast-proofs/alloc/raw_vec/mod.rs/with-directives/raw_vec.rs

Update RawVec proof
